version: '3'

tasks:
  build:
    cmds:
      - task: build:{{OS}}

  build:darwin:
    internal: true
    cmds:
      - cmd: echo "Building for darwin"
        silent: true
      - cmd: go build -o ./bin/letstry-darwin ./cmd/letstry
    env:
      GOOS: darwin
      GOARCH: amd64

  build:linux:
    internal: true
    cmds:
      - cmd: echo "Building for linux"
        silent: true
      - cmd: go build -o ./bin/letstry-linux ./cmd/letstry
    env:
      GOOS: linux
      GOARCH: amd64
  
  build:windows:
    internal: true
    cmds:
      - cmd: echo "Building for windows"
        silent: true
      - cmd: go build -o ./bin/letstry-windows.exe ./cmd/letstry
    env:
      GOOS: windows
      GOARCH: amd64